-- 
-- MySQL Crash Course
-- 
-- Chapter 16 – Creating a Weather Database and Loading Data						
--
-- You can copy and paste any of these commands into your favorite MySQL tool
-- (like MySQL Workbench) and run them in your own MySQL environment.
--
