-- 
-- MySQL Crash Course
-- 
-- Chapter 13 – Creating Events							
--
-- You can copy and paste any of these commands into your favorite MySQL tool
-- (like MySQL Workbench) and run them in your own MySQL environment.
--
