-- 
-- MySQL Crash Course
-- 
-- Chapter 11 – Creating Functions and Procedures							
--
-- You can copy and paste any of these commands into your favorite MySQL tool
-- (like MySQL Workbench) and run them in your own MySQL environment.
--
