-- 
-- MySQL Crash Course
-- 
-- Chapter 15 – Calling MySQL from Programming Languages						
--
-- You can copy and paste any of these commands into your favorite MySQL tool
-- (like MySQL Workbench) and run them in your own MySQL environment.
--
