-- 
-- MySQL Crash Course
-- 
-- Chapter 18 – Using Views to Hide Salary Data							
--
-- You can copy and paste any of these commands into your favorite MySQL tool
-- (like MySQL Workbench) and run them in your own MySQL environment.
--
